// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmE0IFJ9cZDQ84hkHQPH3SZCqgkTVaPjo',
    appId: '1:812519874488:web:6ce03835e14adeaf95794d',
    messagingSenderId: '812519874488',
    projectId: 'kitchen-ai-asf',
    authDomain: 'kitchen-ai-asf.firebaseapp.com',
    storageBucket: 'kitchen-ai-asf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Tin165XxBIu2VDeZ9fadoD14uCUgJ0I',
    appId: '1:812519874488:android:33485ee4501373f795794d',
    messagingSenderId: '812519874488',
    projectId: 'kitchen-ai-asf',
    storageBucket: 'kitchen-ai-asf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_3grQ_wol88yn5GmzvIf8KElYrU2j2Ow',
    appId: '1:812519874488:ios:a9d0bee4a5dd341395794d',
    messagingSenderId: '812519874488',
    projectId: 'kitchen-ai-asf',
    storageBucket: 'kitchen-ai-asf.firebasestorage.app',
    iosBundleId: 'com.example.kitchenAiAsf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_3grQ_wol88yn5GmzvIf8KElYrU2j2Ow',
    appId: '1:812519874488:ios:a9d0bee4a5dd341395794d',
    messagingSenderId: '812519874488',
    projectId: 'kitchen-ai-asf',
    storageBucket: 'kitchen-ai-asf.firebasestorage.app',
    iosBundleId: 'com.example.kitchenAiAsf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmE0IFJ9cZDQ84hkHQPH3SZCqgkTVaPjo',
    appId: '1:812519874488:web:9732ad599af9a77e95794d',
    messagingSenderId: '812519874488',
    projectId: 'kitchen-ai-asf',
    authDomain: 'kitchen-ai-asf.firebaseapp.com',
    storageBucket: 'kitchen-ai-asf.firebasestorage.app',
  );

} 

// ...
