// File generated by FlutterFire CLI.
// ignore_for_file: type=lint


import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDzVEUTF7wkFB3McyXWa72_lLRkKXorfs',
    appId: '1:908117772559:web:206a50037476e1da71967a',
    messagingSenderId: '908117772559',
    projectId: 'kitchen-ai-ed82c',
    authDomain: 'kitchen-ai-ed82c.firebaseapp.com',
    storageBucket: 'kitchen-ai-ed82c.firebasestorage.app',
    measurementId: 'G-Y3G1SFDGV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDKE6yz_B5dGdpZ_KrESyNap6HyPQVgfY',
    appId: '1:908117772559:android:bcf889f761db4c8171967a',
    messagingSenderId: '908117772559',
    projectId: 'kitchen-ai-ed82c',
    storageBucket: 'kitchen-ai-ed82c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBteIhyuNg7BsEL4Tul0BO15rRL07-6HPI',
    appId: '1:908117772559:ios:50ae138987e820a571967a',
    messagingSenderId: '908117772559',
    projectId: 'kitchen-ai-ed82c',
    storageBucket: 'kitchen-ai-ed82c.firebasestorage.app',
    iosBundleId: 'com.example.practiceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBteIhyuNg7BsEL4Tul0BO15rRL07-6HPI',
    appId: '1:908117772559:ios:50ae138987e820a571967a',
    messagingSenderId: '908117772559',
    projectId: 'kitchen-ai-ed82c',
    storageBucket: 'kitchen-ai-ed82c.firebasestorage.app',
    iosBundleId: 'com.example.practiceApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDzVEUTF7wkFB3McyXWa72_lLRkKXorfs',
    appId: '1:908117772559:web:e67b6605ae77b00171967a',
    messagingSenderId: '908117772559',
    projectId: 'kitchen-ai-ed82c',
    authDomain: 'kitchen-ai-ed82c.firebaseapp.com',
    storageBucket: 'kitchen-ai-ed82c.firebasestorage.app',
    measurementId: 'G-C95L1DGP20',
  );
} 

// ...

